#!/bin/bash
# Railway Deployment Script for LifeQuest Backend
# Railway uses GitHub integration, so this script will guide you through setup

echo "🚀 LifeQuest Railway Deployment"
echo "================================"
echo ""
echo "Railway uses GitHub integration for automatic deploys."
echo "Follow these steps:"
echo ""
echo "1. Go to https://railway.app and create an account (if you don't have one)"
echo ""
echo "2. Create a new project:"
echo "   - Click 'New Project'"
echo "   - Select 'Deploy from GitHub repo'"
echo "   - Authorize Railway to access your GitHub account"
echo "   - Select your repo: TreM21-jpg/What-Is-Life-LifeQuest"
echo ""
echo "3. Configure environment:"
echo "   - In the Railway dashboard, click 'Add Service'"
echo "   - Select 'Database' → 'MongoDB' (or use MongoDB Atlas)"
echo ""
echo "4. Set environment variables:"
echo "   - In your service settings, go to 'Variables'"
echo "   - Add: MONGODB_URI = your_atlas_uri_here"
echo "   - If using Railway's MongoDB service, it will auto-set the URI"
echo ""
echo "5. Deploy:"
echo "   - Railway auto-deploys on push to main"
echo "   - Or manually trigger deploy from the dashboard"
echo ""
echo "6. Get your deployment URL:"
echo "   - Your backend will be at: https://your-service.up.railway.app"
echo "   - Update frontend .env.local with REACT_APP_API_URL"
echo ""
echo "For CLI deployment (if Railway CLI is installed):"
echo "  railway link                           # Link to your project"
echo "  railway environment add MONGODB_URI   # Set MongoDB URI"
echo "  railway up                            # Deploy"
echo ""
