#!/bin/bash
# MongoDB Atlas Setup Guide
# Follow these steps to create a free MongoDB cluster

echo "🗄️  MongoDB Atlas Setup Guide"
echo "============================="
echo ""
echo "Step 1: Create MongoDB Account"
echo "------------------------------"
echo "1. Go to https://cloud.mongodb.com"
echo "2. Click 'Sign Up' or 'Sign In'"
echo "3. Create an account (or log in with GitHub)"
echo ""

echo "Step 2: Create a Free Cluster"
echo "-----------------------------"
echo "1. Click 'Create' in the left sidebar"
echo "2. Choose 'Shared' (Free) cluster"
echo "3. Select your cloud provider and region (AWS, default region is fine)"
echo "4. Click 'Create Cluster' (this takes ~3-5 minutes)"
echo ""

echo "Step 3: Create Database User"
echo "----------------------------"
echo "1. In the 'Security' section, click 'Database Access'"
echo "2. Click 'Add New Database User'"
echo "3. Enter:"
echo "   Username: lifequest"
echo "   Password: (generate secure password or create one)"
echo "4. Select 'Built-in Role': 'Atlas admin'"
echo "5. Click 'Add User'"
echo ""

echo "Step 4: Configure Network Access"
echo "--------------------------------"
echo "1. In 'Security', click 'Network Access'"
echo "2. Click 'Add IP Address'"
echo "3. Choose one of:"
echo "   - 'Add Current IP Address' (your IP now)"
echo "   - '0.0.0.0/0' (anywhere - quick testing, not recommended for production)"
echo "4. Click 'Confirm'"
echo ""

echo "Step 5: Get Connection String"
echo "------------------------------"
echo "1. In 'Databases', click 'Connect' on your cluster"
echo "2. Choose 'Connect your application'"
echo "3. Copy the connection string"
echo "4. Replace:"
echo "   <username> with: lifequest"
echo "   <password> with: your_password"
echo "   myFirstDatabase with: lifequest"
echo ""
echo "Example:"
echo "  mongodb+srv://lifequest:yourpass@cluster0.abcd.mongodb.net/lifequest?retryWrites=true&w=majority"
echo ""

echo "Step 6: Set MONGODB_URI in Your Host"
echo "-------------------------------------"
echo "Copy the connection string and run:"
echo ""
echo "For Heroku:"
echo "  heroku config:set MONGODB_URI='your_connection_string' --app=lifequest-api"
echo ""
echo "For Railway:"
echo "  In Dashboard → Variables → Add MONGODB_URI"
echo ""
echo "For AWS EB:"
echo "  eb setenv MONGODB_URI='your_connection_string'"
echo ""
echo "For local testing (.env file):"
echo "  echo 'MONGODB_URI=your_connection_string' >> .env"
echo "  node backend/server-enhanced.js"
echo ""

echo "Step 7: Verify Connection"
echo "------------------------"
echo "Test the endpoint:"
echo "  curl https://your-backend-url/health"
echo ""
echo "Should return:"
echo "  { \"status\": \"ok\", \"database\": \"MongoDB\", ... }"
echo ""
